module: App
module_version: 0.1
title: swiftarr 0.1.0
author: grundoon
# author_url:
github_url: https://github.com/grundoon/swiftarr
github_file_prefix: https://github.com/grundoon/swiftarr/tree/master
# copyright:

swift_version: 5.1.2

theme: fullwidth
skip_undocumented: no
hide_documentation_coverage: no
# head:

min_acl: private

custom_categories:
  - name: Controllers
    children:
    - AdminController
    - AuthController
    - ClientController
    - EventController
    - FezController
    - ForumController
    - TestController
    - TwitarrController
    - UserController
    - UsersController

  - name: Models
    children:
    - Barrel
    - Category
    - Event
    - FezPost
    - Forum
    - ForumPost
    - RegistrationCode
    - Report
    - Token
    - Twarrt
    - User
    - UserNote
    - UserProfile
    
  - name: Enumerations
    children:
    - BarrelType
    - EventType
    - FezType
    - ImageHandlerType
    - LikeType
    - ReportType
    - UserAccessLevel

  - name: Request Structs
    children:
    - BarrelCreateData
    - EventsUpdateData
    - FezContentData
    - ForumCreateData
    - ImageUploadData
    - NoteCreateData
    - NoteUpdateData
    - PostContentData
    - PostCreateData
    - ProfileEditData
    - ReportData
    - UserCreateData
    - UserPasswordData
    - UserRecoveryData
    - UserUsernameData
    - UserVerifyData
    
  - name: Return Structs
    children:
    - AddedUserData
    - AlertKeywordData
    - BarrelData
    - BarrelListData
    - BlockedUserData
    - CategoryData
    - CreatedNoteData
    - CreatedUserData
    - CurrentUserData
    - EventData
    - FezData
    - FezDetailData
    - FezPostData
    - ForumData
    - ForumListData
    - MuteKeywordData
    - MutedUserData
    - NoteData
    - NoteEditData
    - PostData
    - PostDetailData
    - ProfilePublicData
    - SeaMonkey
    - TokenStringData
    - TwarrtData
    - TwarrtDetailData
    - UploadedImageData
    - UserHeader
    - UserInfo
    - UserProfileData
    - UserSearch
    
  - name: Extensions
    children:
    - CharacterSet
    - Date
    - Formatter
    - Future
    - ISO8601DateFormatter
    - JSONDecoder
    - JSONEncoder
    - RouteCollection
    - String
    
  - name: Migrations
    children:
    - AdminUser
    - Categories
    - ClientUsers
    - EventForums
    - Events
    - Forums
    - RegistrationCodes
    - TestUsers

  - name: Pivots
    children:
    - PostLikes
    - TwarrtLikes
    
  - name: Protocols
    children:
    - ContentFilterable
    - ImageHandler
    - UserBookmarkable
    - UserTaggable
    
  - name: Internal Structs/Classes
    children:
    - EventParser
    - ForumEdit
    - ProfileEdit
    - Settings
    - TwarrtEdit
    
